---
title: 'Final Exam: Question 2'
subtitle: "STAT 242: Intermediate Statistics"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(MASS)

leish <- read.csv("https://marievozanne.github.io/stat242/datasets/ecoleish_exam.csv")
```

Leishmaniasis is a zoonotic vector borne disease, which means that it infects both humans and animals, and that is transmitted primarily through the bite of a sand fly. It is endemic (meaning that it persists in the population) in 98 countries. It is endemic in 98 countries in the world and presents a myriad of public health challenges. Domesticated dogs are an integral part of the transmission process, since they spend so much time near humans. Increased understanding the risk factors that lead to clinical leishmaniasis in dogs informs preventative measures to be applied to improve both human and canine health. We will use the following variables in our analysis:

- `Dog_diag_pos`: dog is diagnostically positive for leishmaniasis (response)
- `Dog_Ehrlichia`: dog test result for Ehrlichia (a tickborne disease) (`S=positive`, `N=negative`)
- `House_social_class`: numeric variable quantifying socioeconomic status (higher means increased poverty)
- `Dog_sleeping_loc_reduced`: where the dog sleeps (inside/outside)


In this analysis, we are primarily interested in the following questions:

- Are dogs that are positive for Ehrlichia more likely to be diagnostically positive for leishmaniasis?
- Is the effect of socioeconomic status on the odds of being diagnostically positive for leishmaniasis different for Ehrlichia positive dogs and Ehrlichia negative dogs? 

To answer these questions, complete the following:

### (a) What is the form of the response variable? What is an appropriate model to use, given the form of the response?



### (b) Write down a model that can be used to address both of the questions of interest simultaneously. This should involve no numbers. Be sure to define your notation for your model.



### (c) Using the notation from (b), write down the null and alternative hypotheses corresponding to the two questions of interest above. You should have two sets of hypotheses in total.



### (d) Fit the model you described in (b). You may assume that all model assumptions are satisfied for the purposes of this exam.



### (e) Finish conducting the hypothesis tests that correspond to the hypotheses you wrote in (c). Be sure to state your conclusions in the context of the problem.


### (f) Find the 95% confidence intervals associated with the hypotheses in (c). Interpret them on the odds scale in the context of the problem.


### (g) Briefly summarize your results from (e) and (f). Make them as understandable as possible to a non-technical audience.